---
- name: Generate router configuration files
  hosts: localhost

  roles:
    - members
    - keyservers
    - core_router

- name: Push Junos Configs
  hosts: devices
  roles:
  - Juniper.junos
  connection: local
  gather_facts: no

  vars_prompt:
  - name: USERNAME
    prompt: User name
    private: no
  - name: DEVICE_PASSWORD
    prompt: Device Password
    private: yes

  tasks:
  - name: Checking NETCONF Connectivity
    wait_for: host={{ junos_host }} port=830 timeout=5

  - name: Push Configurations
    junos_install_config:
      user={{ USERNAME }}
      passwd={{ DEVICE_PASSWORD }}
      host={{ junos_host }}
      file=Configs/{{ inventory_hostname }}.set
      overwrite=false
      comment="Configured by MPLSoGREoGroupVPN-Config-Gen"

