---
###########################################################
# BGP Variables:
###########################################################
bgp_group_name: rrCluster1
loopback_net: 1.1.1.0/24
as_num: 65100

route_reflectors:
  - 1.1.1.1
  - 1.1.1.5

